service: my-dynamic-pricing-service # 서비스 이름을 지정합니다.

frameworkVersion: '3'
useDotenv: true # .env 파일을 사용합니다.

provider:
  name: aws
  region: ap-northeast-2 # AWS 리전을 지정합니다. 한국 리전으로 설정했습니다.
  profile: dev # AWS 프로필을 지정합니다.
  architecture: x86_64 # 아키텍처를 x86_64로 설정합니다.
  environment:
    ENV: ${env:ENV} # 환경 변수를 설정합니다.

  ecr:
    images:
      dynamic-pricing-image: # 이미지 이름을 지정합니다. 이름을 변경했습니다.
        path: ./ # Dockerfile이 위치한 경로를 지정합니다.

functions:
  app:
    memorySize: 512 # 람다 함수의 메모리 크기를 설정합니다.
    timeout: 29 # 타임아웃을 설정합니다. API Gateway의 최대 타임아웃은 30초입니다.
    image:
      name: dynamic-pricing-image # 사용할 이미지 이름을 지정합니다. 이름을 변경했습니다.
      command:
        - '/app/dist/lambda.handler' # 람다 핸들러의 위치를 지정합니다.
    events:
      - httpApi:
          method: '*' # 모든 HTTP 메서드를 허용합니다.
          path: '*' # 모든 경로를 허용합니다.
      - schedule:
          name: morningScrapping # 이벤트 이름을 지정합니다.
          description: 'Trigger scrapping at 11 AM every day' # 이벤트 설명을 추가합니다.
          rate: cron(0 11 * * ? *) # 매일 오전 11시에 실행합니다.
          enabled: true # 스케줄링을 활성화합니다.
      - schedule:
          name: eveningScrapping # 이벤트 이름을 지정합니다.
          description: 'Trigger scrapping at 8 PM every day' # 이벤트 설명을 추가합니다.
          rate: cron(0 20 * * ? *) # 매일 오후 8시에 실행합니다.
          enabled: true # 스케줄링을 활성화합니다.
